# Generated by Django 4.2.23 on 2026-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter with country code, e.g., 251911223344', max_length=20, null=True),
        ),
    ]
