# Generated by Django 4.2.23 on 2026-02-17 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skyport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('icon_identifier', models.CharField(blank=True, help_text="e.g. 'laptop_mac'", max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='passenger_icons/')),
                ('is_active', models.BooleanField(default=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('passenger', 'name')},
            },
        ),
    ]
