# Generated by Django 4.2.23 on 2026-01-02 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skyport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='departure_date',
        ),
        migrations.AddField(
            model_name='trip',
            name='cosmetic_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='laptop_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='mobile_fee',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='other_fee_base',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
